#pragma once
#include <vector>
#include <memory>
#include "entityrepository.h"
#include "component\component_base.h"
#include "component\temporalstatecomponent.h"
#include "component\physicalcomponent.h"
#include "component\thrustcomponent.h"
#include "component\horizontalorientcomponent.h"
#include "component\collisioncomponent.h"
#include "component\poweredbodycomponent.h"
#include "component\radartrackablecomponent.h"
#include "component\textplatecomponent.h"
#include "component\playercomponent.h"
#include "component\firebulletscomponent.h"
#include "component\stationcomponent.h"